### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by mw-zou** [BrenoCPimenta/PokerAI#1]
I have encountered some difficulties in PokerAI recently, Can you tell me about the input and output format of the model？Or provide a demo. thank you.

**Comment by BrenoCPimenta** [comment]
First of all, has to be mentioned that the key part of this study is the data treatment, however, since it is known that this type of application is used for controversial purposes, an agreement has been made on not to publish the entire treatment done by the research. But it is noteworthy that a relevant part of it is presented on the data folder, it is sparse, but with a good in depth study most of the idea can be understood.

* **Input**:
    * **First**: the net will be fed by a succession of the table situations that happened before: which player in which table position in which turn, with which pot size, with which 'potential' of cards on the table, took which decision.
    * **Second**: feed the current situation to the network, with all the features above except for action (for obvious reasons) and 'potential' from table cards. Another feature is fed as well, the current hand strength, calculated based on the cards of the players with the cards on the table.

* **Output** is which action should the machine do by the situation given:
F-fold; C-check/call; RS-small-raise; RM-medium-raise; RB-big-raise.
By literal means, the output must be a number on your normalization choice on data treatment process that will imply on one of the actions above.

If you are looking into Neural Networks for poker bots I suggest taking a look at [DeepStack](https://www.deepstack.ai/), by the time of this work it was the state of the art on poker bots using this method. Although it was developed for HeadsUp poker, it has significant potential in 6-players, as explained by Michael Bowling on one of his seminars about it. The Poker AI repository work focus on trying to understand the possibilities on Recurrent NNs for this kind of incomplete information games, but by a stand alone technique it doesn't present as good results as the DeepStack with a mixed techniques method.
